#!/usr/bin/env bash
#
# @license BSD-3-Clause
#
# Copyright (c) 2019 Project Jupyter Contributors.
# Distributed under the terms of the 3-Clause BSD License.

set -o errexit
set -o xtrace

exec jupyter lab --dev --NotebookApp.allow_remote_access=True --no-browser --debug --ip 0.0.0.0 "${@:3}"